version: '3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./src:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.services.apache.loadbalancer.server.port=80"

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${PROJECT_BASE_URL}`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

  traefik:
      image: "traefik:v2.6"
      command: --api.insecure=true --providers.docker
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"