version: '3'

services:

  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./:/var/www"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.services.apache.loadbalancer.server.port=80"
    env_file:
        - ./.env

  traefik:
      image: traefik:v2.6
      container_name: traefik
      command: --api.insecure=true --providers.docker
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"