version: '3'
services:
  appache:
    image: httpd:2.4.52
    ports:
      - 80:80
    volumes:
      - "./src:/usr/local/apache2/htdocs"

  database:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=test
      - MARIADB_USER=user
      - MARIADB_PASSWORD=pass

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1